apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-db.fullname" . }}-service
  labels:
    {{- include "backend-db.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "backend-db.name" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
