apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-db.fullname" . }}-postgres
  labels:
    {{- include "backend-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase }}
