apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 3000
  type: ClusterIP
