apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-service
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "backend.name" . }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
