apiVersion: v1
kind: Secret
metadata:
  name: postgresql-user-secret
  namespace: {{ .Values.backend.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  POSTGRES_USER: {{ .Values.backend.postgresqlUser | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password-secret
  namespace: {{ .Values.backend.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.backend.postgresqlPassword | b64enc | quote }}

